server:
  port: 8001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_agency
    username: root
    password: mysql%admin%
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update